feature/tsconfig/export
degordian/js-coding-standards pull request #4
Opened 2018-01-24 11:13 UTC by bonzzy

Prepared `tsconfig` standard for easy usage in projects

2018-01-24 11:17 UTC, tonymrakovcic commented on docs/typescript/tsconfig/tsconfig.json
> +    "sourceRoot": "src/ts",                    /* Specify the location where debugger should locate TypeScript files instead of source locations. */
shoudnt this be just src?

2018-01-24 12:00 UTC, bonzzy commented on docs/typescript/tsconfig/tsconfig.json
> +    "sourceRoot": "src/ts",                    /* Specify the location where debugger should locate TypeScript files instead of source locations. */
yes I think so too 👍

2018-01-24 12:17 UTC, vilimco requested changes

2018-01-24 12:17 UTC, jewbre commented on docs/typescript/tsconfig/tsconfig.json
> +    "typeRoots": ["node_modules/@types", "src/types"], /* List of folders to include type definitions from. */
ne treba node_modules, @types se resolvea u node_modules/@types.

Nisam siguran, ali generalno postoji mogucnost da se node_modules ne zove node_modules, ovako imamo pokriveno uvijek :)

2018-01-24 12:17 UTC, jewbre commented on docs/typescript/tsconfig/tsconfig.json
> +    "sourceRoot": "src/",                    /* Specify the location where debugger should locate TypeScript files instead of source locations. */
trailing slash je tu radi?
Maknuti.

2018-01-24 12:25 UTC, tonymrakovcic commented on docs/typescript/tsconfig/tsconfig.json
> +    "typeRoots": ["node_modules/@types", "src/types"], /* List of folders to include type definitions from. */
ne znam dal mislis na ovo - https://github.com/npm/npm/issues/2734#issuecomment-7919638
Ali s njihove strane se sam string "node_modules" nece mijenjat :)
Samo digresija, kuzim kaj mislis inace :)

2018-01-24 12:28 UTC, krukru commented on docs/typescript/tsconfig/tsconfig.json
> +    "typeRoots": ["node_modules/@types", "src/types"], /* List of folders to include type definitions from. */
Meni se ne kompajliraju testovi ako imam `@types`, dok `node_modules/@types` radi

2018-01-24 12:33 UTC, bonzzy commented on docs/typescript/tsconfig/tsconfig.json
> +    "typeRoots": ["node_modules/@types", "src/types"], /* List of folders to include type definitions from. */
meni također radi samo dok je `node_modules/@types`

2018-01-24 12:45 UTC, jewbre commented on docs/typescript/tsconfig/tsconfig.json
> +    "typeRoots": ["node_modules/@types", "src/types"], /* List of folders to include type definitions from. */
hmm, dost zanimljivo. Nek ostane onda ovako.

Meni radi samo ```@types```, cak i za jasmine testove koje sam vrtio na onom svom setupu :/

2018-01-24 12:45 UTC, vilimco approved these changes

2018-01-25 13:28 UTC, krukru commented
Same thing as with tslint.json, the config file is in docs folder. Other than that, I see that @jewbre approved so I will assume the doc is final (for now)

2018-01-25 13:28 UTC, merged